import { markdownToHTML } from "@/core/markdown.js";
import { JsonAttachment, JsonButtonComponent, JsonButtonStyle, JsonComponentType, JsonData, JsonEmbed, JsonMessage, JsonPoll, JsonReaction, JsonSelectMenu, JsonTopLevelComponent } from "../../types/types.js";
import { ACTIONROW_CSS, ATTACHMENT_CSS, BUTTON_CSS, COMPONENTS_CSS, COMPONENTSV2_CSS, DEFAULT_CSS, EMBED_CSS, MESSAGE_CSS, POLL_CSS, POLL_RESULT_EMBED_CSS, REACTIONS_CSS } from "./css.js";
import { script } from "./js.js";
import packageJson from "package.json" with { type: 'json' };
import { sanitize } from "@/core/sanitizer.js";
import highlightHash from "@/assets/highlightJsHash.json" with { type: 'json'};
import transcriptHash from "@/assets/transcriptHash.json" with { type: 'json'};

const FILE_SIZE_UNIT = ["KB", "MB", "GB", "TB"];
const FILE_SIZE_THRESHOLD = 512;
const BUTTON_COLORS = {
  1: "#5865f2", // Primary
  2: "#323538", // Secondary
  3: "#32c05f", // Sucess
  4: "#be3638", // Danger
  5: "#323538", // Link
  6: "#5865f2"  // Premium 
};
const ICONS = {
  Reply: "reply-icon",
  Download: "download-icon",
  Link: "link-icon",
};
const TEXT = {
  TranscriptFooter: 'Transcript generated by <a href="https://github.com/HenriqueMairesse/discord-message-transcript">discord-message-transcript</a>',
  Spoiler: "SPOILER",
  File: {
    DefaultName: "attachment",
    Unavailable: {
        Video: "Video unavailable",
        Audio: "Audio unavailable",
    }
  },
  Pool: {
    Closed: " • Poll closed",
  }
};


export class Html {
    data: JsonData;
    dateFormat: Intl.DateTimeFormat;

    constructor(data: JsonData) {
        this.data = data;
        try {
            this.dateFormat = new Intl.DateTimeFormat(data.options.localDate, {
                timeZone: data.options.timeZone,
                day: '2-digit',
                month: '2-digit',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
                second: '2-digit'
            });
        } catch (error) {
            throw new Error("[discord-message-transcript] Invalid LocalDate and/or TimeZone.");
        }
    }

    private getIcon(): string {
        const { guild, channel } = this.data;
        if (guild) {
            if (guild.icon) {
                return `<img src="${guild.icon}" style="width: 7rem; height: 7rem; border-radius: 50%;">`;
            } else {
                return `<div class="guildInitialsIcon">${initials(guild.name)}</div>`;
            }
        } else {
            return `<img src="${channel.img}" style="width: 7rem; height: 7rem; border-radius: 50%;">`;
        }

        function initials(name: string) {
            const words = name.split(' ').filter(word => word.length > 0);
            if (words.length >= 1) {
                return words.map(word => word[0]).join('').substring(0, 3).toUpperCase();
            }
            return name.substring(0, 1).toUpperCase();
        }
    }

    private headerBuilder() {
        const { channel, guild } = this.data;
    
        return `
        <div style="display: flex;  gap: 1.5rem; align-items: center; width 100vw">
            ${this.getIcon()}
            <div style="display: flex; flex-direction: column; justify-content: center; gap: 1.25rem;">
                ${guild ? `<div id="guild" class="line">
                    <h4>Guild: </h4>
                    <h4 style="font-weight: normal;">${sanitize(guild.name)}</h4>
                </div>` : ""}
                ${channel.parent ? `<div id="category" class="line">
                    <h4>Category: </h4>
                    <h4 style="font-weight: normal;">${sanitize(channel.parent.name)}</h4>
                </div>` : ""}
                <div id="channel" class="line">
                    <h4>Channel: </h4>
                    <h4 style="font-weight: normal;">${sanitize(channel.name)}</h4>
                </div>
                ${channel.topic ? `<div id="topic" class="line">
                    <h4>Topic: </h4>
                    <h4 style="font-weight: normal;">${sanitize(channel.topic)}</h4>
                </div>` : ""}
            </div>
        </div>
        `;
    }

    private async messagesBuilder() {
        return (await Promise.all(this.data.messages.map(async message => {
            const date = new Date(message.createdTimestamp);
            
            return `
<div class="messageDiv" id="${sanitize(message.id)}" data-author-id="${sanitize(message.authorId)}">
    ${message.references && message.references.messageId ? 
    `<div class="messageReply" data-id="${sanitize(message.references.messageId)}">
        <svg class="messageReplySvg"><use href="#${ICONS.Reply}"></use></svg>
        <img class="messageReplyImg" src="">
        <div class="replyBadges"></div>
        <div class="messageReplyText"></div>
    </div>` : ""}
    <div class="messageBotton">
        <img src="" class="messageImg">
        <div class="messageDivRight">
            <div class="messageUser">
                <h3 class="messageUsername"></h3>
                <div class="badges"></div>
                <p class="messageTimeStamp">${this.dateFormat.format(date)}</p>
            </div>
            <div class="messageContent">${markdownToHTML(message.content, this.data.mentions, message.mentions, this.dateFormat)}</div>
            ${message.poll ? this.pollBuilder(message.poll) : ""}
            ${message.embeds.length > 0 ? this.embedBuilder(message, message.embeds) : ""}
            ${message.attachments.length > 0 ? this.attachmentBuilder(message.attachments) : ""}
            ${message.components.length > 0 ? this.componentBuilder(message, message.components) : ""}
            ${message.reactions.length > 0 ? this.reactionsBuilder(message.reactions) : ""}
        </div>
    </div>
</div>
        `;
        }))).join("");
    }

    async toHTML() {
        const { options } = this.data;
        const cssContent = `
            ${DEFAULT_CSS}
            ${MESSAGE_CSS}
            ${options.includePolls ? POLL_CSS + POLL_RESULT_EMBED_CSS : ""}
            ${options.includeEmbeds ? EMBED_CSS : ""}
            ${options.includeButtons || options.includeComponents ? ACTIONROW_CSS : ""}
            ${options.includeAttachments || options.includeV2Components ? ATTACHMENT_CSS : ""}
            ${options.includeButtons || options.includeV2Components ? BUTTON_CSS : ""}
            ${options.includeComponents ? COMPONENTS_CSS : ""}
            ${options.includeV2Components ? COMPONENTSV2_CSS : ""}
            ${options.includeReactions ? REACTIONS_CSS : ""}
        `;

        const jsContent = script(options.includeComponents, options.includePolls);

        return `
<!DOCTYPE html>
<html lang="${options.localDate}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${sanitize(options.fileName)}</title>
    <link rel="stylesheet" integrity="${highlightHash.style}" crossorigin="anonymous" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build/styles/atom-one-dark.min.css">
    <script integrity="${highlightHash.script}" crossorigin="anonymous" src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build/highlight.min.js"></script>
    ${options.selfContained ? `<style>${cssContent}</style>` : `<link rel="stylesheet" integrity="${transcriptHash.style}" crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/discord-message-transcript-base@${packageJson.version}/dist/assets/style.css">`}
</head>
<body>
    ${this.svgBuilder()}
    <header>
        ${this.headerBuilder()}
    </header>
    <main style="display: flex; flex-direction: column; padding: 2.25%; flex: 1;">
       ${await this.messagesBuilder()}
    </main>
    ${options.watermark ? `<footer>
        <br>
        <div style="padding: 1rem 0; font-weight: 700; text-align: center; font-size: 1.5rem; background-color: #2b2d31;">${TEXT.TranscriptFooter}</div>
    </footer> ` : ""}
    <script id="authorData" type="application/json">
        ${JSON.stringify({ authors: this.data.authors })}
    </script>
    ${options.selfContained ? `<script>${jsContent}</script>` : `<script integrity="${transcriptHash.script}" crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/discord-message-transcript-base@${packageJson.version}/dist/assets/script.js"></script>`}
</body>
</html>
        `;
    }

    private pollBuilder(poll: JsonPoll): string {
        const totalVotes = poll.answers.reduce((acc, answer) => acc + answer.count, 0);

        let footerText = `${totalVotes} votes`;
        if (poll.isFinalized) {
            footerText += TEXT.Pool.Closed;
        } else if (poll.expiry) {
            footerText += ` • ${poll.expiry}`;
        }

        return `
        <div class="pollDiv">
            <div class="pollQuestion">${sanitize(poll.question)}</div>
            <div class="pollAnswers">
                ${poll.answers.map(answer => {
                    const voteCount = answer.count;
                    const percentage = totalVotes > 0 ? (voteCount / totalVotes) * 100 : 0;

                    return `
                    <div class="pollAnswer">
                        <div class="pollAnswerBar" style="width: ${percentage}%;"></div>
                        <div class="pollAnswerContent">
                            <div class="pollAnswerDetails">
                                ${answer.emoji ? `<div class="pollAnswerEmoji">${answer.emoji.name ? sanitize(answer.emoji.name) : ""}</div>` : ''}
                                <div class="pollAnswerText">${sanitize(answer.text)}</div>
                            </div>
                            <div class="pollAnswerVotes">${voteCount}</div>
                        </div>
                    </div>
                    `;
                }).join('')}
            </div>
            <div class="pollFooter">${sanitize(footerText)}</div>
        </div>
        `;
    }
    
    private pollResultEmbedBuilder(embed: JsonEmbed, message: JsonMessage): string {
        const getField = (name: string) => embed.fields?.find(f => f.name === name)?.value;
        const winnerText = getField("victor_answer_text");
        const emojiText = getField("victor_answer_emoji_name");
        const winnerVotes = parseInt(getField("victor_answer_votes") ?? "0");
        const totalVotes = parseInt(getField("total_votes") ?? "0");
        const winnerPercentage = totalVotes > 0 ? (winnerVotes / totalVotes) * 100 : 0;

        return `
        <div class="pollResultEmbed">
            <div>
                <div class="pollResultEmbedWinner">
                    ${emojiText ? sanitize(emojiText) : ""}
                    ${winnerText ? sanitize(winnerText) : winnerVotes > 0 ? "The result was a draw" : "There was no winner"}
                    ${winnerVotes != 0 ? `<span class="pollResultEmbedCheckmark">✔</span>` : ""}
                </div>
                <div class="pollResultEmbedSubtitle">${totalVotes} votes (${winnerPercentage.toFixed(1)}%)</div>
            </div>
            <div class="pollResultEmbedButtonDiv">
                <div data-id="${message.references?.messageId ?? ""}" class="pollResultEmbedButton">View Poll</div>
            </div>
        </div>
        `;
    }

    private embedBuilder(message: JsonMessage, embeds: JsonEmbed[]): string {
        return embeds.map(embed => {
            if (embed.type === 'poll_result') return this.pollResultEmbedBuilder(embed, message);

            if (!this.data.options.includeEmbeds) return "";
            const embedAuthor = embed.author ? (embed.author.url ? `<a class="embedHeaderLefttAuthorName" href="${sanitize(embed.author.url)}" target="_blank">${sanitize(embed.author.name)}</a>` : `<p class="embedHeaderLeftAuthorName">${sanitize(embed.author.name)}</p>`) : "";
            const embedTitle = embed.title ? (embed.url ? `<a class="embedHeaderLeftTitle" href="${sanitize(embed.url)}" target="_blank">${sanitize(embed.title)}</a>` : `<p class="embedHeaderLeftTitle">${sanitize(embed.title)}</p>`) : "";

            return `
                <div class="embed" style="border-left-color:${embed.hexColor ? `${embed.hexColor}` : '#4f545c'}">
                    ${embed.author || embed.title || embed.thumbnail || embed.description ? `
                    <div class="embedHeader">
                        <div class="embedHeaderLeft">
                            ${embed.author ? `
                            <div class="embedHeaderLeftAuthor">
                                ${embed.author.iconURL ? `<img class="embedHeaderLeftAuthorImg" src="${embed.author.iconURL}">` : ""}
                                ${embedAuthor}
                            </div>` : ""}
                            ${embedTitle}
                            ${embed.description ? `<div class="embedDescription">${markdownToHTML(embed.description, this.data.mentions, message.mentions, this.dateFormat)}</div>` : ""}
                        </div>
                        ${embed.thumbnail ? `<img class="embedHeaderThumbnail" src="${embed.thumbnail.url}">` : ""}
                    </div>` : ""}
                    ${embed.fields && embed.fields.length > 0 ? `
                    <div class="embedFields">
                        ${embed.fields.map(field => `
                        <div class="${field.inline ? "embedFieldsFieldInline" : "embedFieldsField"}">
                            <p class="embedFieldsFieldTitle">${sanitize(field.name)}</p>
                            <p class="embedFieldsFieldValue">${markdownToHTML(field.value, this.data.mentions, message.mentions, this.dateFormat)}</p>
                        </div>`).join("")}
                    </div>` : ""}
                    ${embed.image ? `
                    <div class="embedImage">
                        <img src="${embed.image.url}">
                    </div>` : ""}
                    ${embed.footer || embed.timestamp ? `
                    <div class="embedFooter">
                        ${embed.footer?.iconURL ? `<img class="embedFooterImg" src="${embed.footer.iconURL}">` : ""}
                        ${embed.footer?.text || embed.timestamp ? `<p class="embedFooterText">${embed.footer?.text ? sanitize(embed.footer.text) : ''}${embed.footer?.text && embed.timestamp ? ' | ' : ''}${embed.timestamp ? this.dateFormat.format(new Date(embed.timestamp)) : ''}</p>` : ""}
                    </div>` : ""}
                </div>
            `;
        }).join("");
    }

    private attachmentBuilder(attachments: JsonAttachment[]): string {
        return attachments.map(attachment => {
            let html = "";

            if (attachment.contentType?.startsWith('image/')) {
                html = `<img class="attachmentImage" src="${attachment.url}">`;
            } else if (attachment.contentType?.startsWith('video/')) {
                if (attachment.url == "") {
                    html = `<video class="attachmentVideo" controls src="${attachment.url}"></video>`;
                } else {
                    html = `<div class="attachmentVideoUnavailable">${TEXT.File.Unavailable.Video}</div>`;
                }
            } else if (attachment.contentType?.startsWith('audio/')) {
                if (attachment.url == "") {
                    html = `<audio class="attachmentAudio" controls src="${attachment.url}"></audio>`;
                } else {
                    html = `<div class="attachmentAudioUnavailable">${TEXT.File.Unavailable.Audio}</div>`;
                }
            } else {
                let fileSize = attachment.size / 1024;
                let count = 0;
                while (fileSize > FILE_SIZE_THRESHOLD && count < FILE_SIZE_UNIT.length - 1) {
                    fileSize = fileSize / 1024;
                    count++;
                }

                html = `
                    <div class="attachmentFile">
                        <div class="attachmentFileInfo">
                            <p class="attachmentFileName">${attachment.name ? sanitize(attachment.name) : TEXT.File.DefaultName}</p>
                            <div class="attachmentFileSize">${fileSize.toFixed(2)} ${FILE_SIZE_UNIT[count]}</div>
                        </div>
                        ${attachment.url != "" ? 
                        `<a class="attachmentDownload" href="${attachment.url}" target="_blank">
                            <svg class="attachmentDownloadIcon"><use href="#${ICONS.Download}"></use></svg>
                        </a>` :
                        `<span class="attachmentDownload">
                            <svg class="attachmentDownloadIcon"><use href="#${ICONS.Download}"></use></svg>
                        </span>`}
                    </div>
                `;
            }

            return this.spoilerAttachmentBuilder(attachment.spoiler, html);
        }).join("");
    }

    private componentBuilder(message: JsonMessage, components: JsonTopLevelComponent[]): string {
        return components.map(component => {
            switch (component.type) {
                case JsonComponentType.ActionRow: {
                    if (!component.components[0]) return "";

                    return `
                    <div class="actionRow">
                        ${component.components[0].type == JsonComponentType.Button ? component.components.map(button => {
                            return button.type == JsonComponentType.Button ? this.buttonBuilder(button) : "";
                        }).join("") : this.selectorBuilder(component.components[0])}
                    </div>
                    `;
                }

                case JsonComponentType.Container: {

                    const html = `
                    <div class="container" style="border-left-color: ${component.hexAccentColor}">
                        ${this.componentBuilder(message, component.components)}
                    </div>
                    `;
                    return this.spoilerAttachmentBuilder(component.spoiler, html);
                }

                case JsonComponentType.File: {
                    
                    let fileSize = (component.size ?? 0) / 1024;
                    let count = 0;
                    while (fileSize > FILE_SIZE_THRESHOLD && count < FILE_SIZE_UNIT.length - 1) {
                        fileSize = fileSize / 1024;
                        count++;
                    }

                    const html = `
                        <div class="attachmentFile">
                            <div class="attachmentFileInfo">
                                <p class="attachmentFileName">${component.fileName ? sanitize(component.fileName) : TEXT.File.DefaultName}</p>
                                <div class="attachmentFileSize">${fileSize.toFixed(2)} ${FILE_SIZE_UNIT[count]}</div>
                            </div>
                            ${component.url != "" ? 
                            `<a class="attachmentDownload" href="${component.url}" target="_blank">
                                <svg class="attachmentDownloadIcon"><use href="#${ICONS.Download}"></use></svg>
                            </a>` :
                            `<span class="attachmentDownload">
                                <svg class="attachmentDownloadIcon"><use href="#${ICONS.Download}"></use></svg>
                            </span>`}
                        </div>
                    `;

                    return this.spoilerAttachmentBuilder(component.spoiler, html);
                }

                case JsonComponentType.MediaGallery: {
                    return `
                    <div class="mediaGallery"> 
                        ${component.items.map(image => {
                            return `
                            <div class="mediaGalleryItem"> 
                                ${this.spoilerAttachmentBuilder(image.spoiler, `<img class="mediaGalleryImg" src="${image.media.url}">`)}
                            </div>
                            `    
                        }).join("")}
                    </div>
                    `
                }

                case JsonComponentType.Section: {
                    return `
                    <div class="section">
                        <div class="sectionLeft">
                            ${this.componentBuilder(message, component.components)}
                        </div>
                        <div class="sectionRight">
                            ${component.accessory.type == JsonComponentType.Button ? this.buttonBuilder(component.accessory)
                            : component.accessory.type == JsonComponentType.Thumbnail ? this.spoilerAttachmentBuilder(component.accessory.spoiler, `
                            <img class="sectionThumbnail" src="${component.accessory.media.url}">
                            `) : ""
                            }
                        </div>
                    </div> 
                    `
                }

                case JsonComponentType.Separator: {
                    return `<hr class="separator" style="${component.divider ? "" : "visibility: hidden;"} ${component.spacing == 1 ? "margin: 0.15rem 0;" : "margin: 0.3rem 0;"}">`
                }

                case JsonComponentType.TextDisplay: {
                    return `<div class="textDisplay">${markdownToHTML(component.content, this.data.mentions, message.mentions, this.dateFormat)}</div>`;
                }
            
                default:
                    return ``;
            }
        }).join("");
    }

    private buttonBuilder(button: JsonButtonComponent): string {
        return `
        <div class="button" style="background-color: ${BUTTON_COLORS[button.style]}">
            ${button.style == JsonButtonStyle.Link && button.url ? `
            <a class="buttonLink" href="${sanitize(button.url)}" target="_blank">
                ${button.emoji ? `<p class="buttonEmoji">${sanitize(button.emoji)}</p>` : ""}
                ${button.label ? `<p class="buttonLabel">${sanitize(button.label)}</p>` : ""}
                <svg class="buttonLinkIcon"><use href="#${ICONS.Link}"></use></svg>
            </a>` : `
                ${button.emoji ? `<p class="buttonEmoji">${sanitize(button.emoji)}</p>` : ""}
                ${button.label ? `<p class="buttonLabel">${sanitize(button.label)}</p>` : ""}
            `}
        </div>
        `;
    }

    private selectorBuilder(selector: JsonSelectMenu): string {
        return `
        <div class="selector">
            <div class="selectorInput">
                <p class="selectorInputText">${selector.placeholder ? sanitize(selector.placeholder) : ""}</p>
            </div>
            <div class="selectorOptionMenu">
                ${selector.type == JsonComponentType.StringSelect ? selector.options.map(option => {
                    return `
                    <div class="selectorOption">
                        ${option.emoji ? `<p class="selectorOptionEmoji">${option.emoji.name ? sanitize(option.emoji.name) : ""}</p>` : ""}
                        <div class="selectorOptionRight">
                            <p class="selectorOptionTitle">${sanitize(option.label)}</p>
                            ${option.description ? `<p class="selectorOptionDesc">${sanitize(option.description)}</p>` : ""}
                        </div>
                    </div>
                    `;
                }).join("") : ""}
            </div>
        </div>
        `;
    }

    private reactionsBuilder(reactions: JsonReaction[]): string {
        return `
            <div class="reactionsDiv">
                ${reactions.map(reaction => `
                    <div class="reaction"><p>${reaction.count} ${sanitize(reaction.emoji)}</p></div>
                `).join('')}
            </div>
        `;
    }

    private spoilerAttachmentBuilder(spoiler: boolean, html: string): string {
        return spoiler ? `<div class="spoilerAttachment"><div class="spoilerAttachmentOverlay">${TEXT.Spoiler}</div><div class="spoilerAttachmentContent">${html}</div></div>` : html;
    }

    private svgBuilder() {
        const { options } = this.data;
        return `
    <svg style="display: none;">
        <defs>
            <symbol id="${ICONS.Reply}" viewBox="0 0 16 16" fill="none">
                <g transform="rotate(90 8 8)">
                    <path d="M6 2V9C6 11.5 8.5 14 11 14H14" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
                </g>
            </symbol>
            ${options.includeAttachments ? `<symbol id="${ICONS.Download}" viewBox="0 -960 960 960">
                <path d="m720-120 160-160-56-56-64 64v-167h-80v167l-64-64-56 56 160 160ZM560 0v-80h320V0H560ZM240-160q-33 0-56.5-23.5T160-240v-560q0-33 23.5-56.5T240-880h280l240 240v121h-80v-81H480v-200H240v560h240v80H240Zm0-80v-560 560Z"/>
            </symbol> ` : ""}
            ${options.includeButtons ? `<symbol id="${ICONS.Link}" viewBox="0 -960 960 960" fill="#e3e3e3">
                <path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h560v-280h80v280q0 33-23.5 56.5T760-120H200Zm188-212-56-56 372-372H560v-80h280v280h-80v-144L388-332Z"/>
            </symbol>` : ""}
        </defs>
    </svg>
    `;
    }
}