import { describe, expect, it } from "vitest";
import { Html } from "../../../src/renderers/html/html";

function createData(overrides: Partial<any> = {}) {
  return {
    authors: [],
    channel: {
      id: "c1",
      img: "https://channel.test/img.png",
      name: "general",
      parent: null,
      topic: null,
    },
    guild: {
      id: "g1",
      name: "My Guild",
      icon: null,
    },
    messages: [],
    mentions: { channels: [], roles: [], users: [] },
    options: {
      localDate: "en-US",
      timeZone: "UTC",
      fileName: "transcript <unsafe>.html",
      includePolls: false,
      includeEmbeds: false,
      includeButtons: false,
      includeComponents: false,
      includeAttachments: false,
      includeV2Components: false,
      includeReactions: false,
      selfContained: true,
      watermark: true,
    },
    ...overrides,
  };
}

describe("renderers/html/html.ts", () => {
  it("throws for invalid locale/timezone configuration", () => {
    expect(
      () =>
        new Html(
          createData({
            options: {
              ...createData().options,
              localDate: "invalid-locale",
              timeZone: "Invalid/Zone",
            },
          }) as any,
        ),
    ).toThrow("[discord-message-transcript] Invalid LocalDate and/or TimeZone.");
  });

  it("renders self-contained HTML with sanitized title and footer watermark", async () => {
    const html = new Html(createData() as any);
    const result = await html.toHTML();

    expect(result).toContain("<!DOCTYPE html>");
    expect(result).toContain("<style>");
    expect(result).toContain("Transcript generated by");
    expect(result).toContain("<title>transcript &lt;unsafe&gt;.html</title>");
    expect(result).toContain("guildInitialsIcon");
  });

  it("renders CDN assets when selfContained is false", async () => {
    const html = new Html(
      createData({
        guild: null,
        options: {
          ...createData().options,
          selfContained: false,
          watermark: false,
        },
      }) as any,
    );

    const result = await html.toHTML();

    expect(result).toContain("cdn.jsdelivr.net/npm/discord-message-transcript-base@");
    expect(result).not.toContain("<style>");
    expect(result).not.toContain("footerWatermark");
  });

  it("renders message blocks for embed, attachment and reactions", async () => {
    const html = new Html(
      createData({
        mentions: { channels: [], roles: [], users: [] },
        messages: [
          {
            id: "m1",
            authorId: "u1",
            content: "hello **world**",
            createdTimestamp: 1700000000000,
            mentions: false,
            system: false,
            references: null,
            poll: null,
            embeds: [
              {
                type: "rich",
                author: null,
                title: "Embed title",
                url: null,
                description: "embed body",
                fields: [],
                footer: null,
                timestamp: null,
                thumbnail: null,
                image: null,
                hexColor: "#112233",
              },
            ],
            attachments: [
              {
                contentType: "image/png",
                name: "image.png",
                spoiler: false,
                size: 1024,
                url: "https://img.test/a.png",
              },
            ],
            components: [],
            reactions: [{ emoji: "👍", count: 2 }],
          },
        ],
        options: {
          ...createData().options,
          includeEmbeds: true,
          includeAttachments: true,
          includeReactions: true,
        },
      }) as any,
    );

    const result = await html.toHTML();
    const mainFragment = result.match(/<main>[\s\S]*<\/main>/)?.[0] ?? "";

    expect(mainFragment).toContain('class="messageDiv" id="m1"');
    expect(mainFragment).toContain('class="embed"');
    expect(mainFragment).toContain('class="attachmentImage"');
    expect(mainFragment).toContain('class="reactionsDiv"');

    const normalizedMain = mainFragment
      .replace(/<p class="messageTimeStamp">[\s\S]*?<\/p>/g, "<p class=\"messageTimeStamp\">[TIMESTAMP]</p>")
      .replace(/\s+/g, " ")
      .trim();

    expect(normalizedMain).toContain('class="messageDiv" id="m1"');
    expect(normalizedMain).toContain('class="embed" style="border-left-color:#112233"');
    expect(normalizedMain).toContain('class="attachmentImage" src="https://img.test/a.png"');
    expect(normalizedMain).toContain('<p class="messageTimeStamp">[TIMESTAMP]</p>');
  });
});
